# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createnewuser.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(615, 660)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: rgb(191, 234, 209);")
        self.formFrame = QtWidgets.QFrame(Form)
        self.formFrame.setGeometry(QtCore.QRect(50, 120, 521, 441))
        self.formFrame.setStyleSheet("")
        self.formFrame.setObjectName("formFrame")
        self.formLayout = QtWidgets.QFormLayout(self.formFrame)
        self.formLayout.setContentsMargins(7, 7, 7, 7)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_register = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_register.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_register.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_register.setObjectName("lineEdit_register")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_register)
        self.label_4 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_name = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_name.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_name)
        self.label_5 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_surname = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_surname.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_surname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_surname.setObjectName("lineEdit_surname")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_surname)
        self.label_12 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_age = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_age.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_age.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_age.setObjectName("lineEdit_age")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_age)
        self.label_2 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_username = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_username.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_username.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_username)
        self.label_3 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_password = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_password.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_password.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_password)
        self.label_6 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.comboBox_dept = QtWidgets.QComboBox(self.formFrame)
        self.comboBox_dept.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_dept.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_dept.setObjectName("comboBox_dept")
        self.comboBox_dept.addItem("")
        self.comboBox_dept.addItem("")
        self.comboBox_dept.addItem("")
        self.comboBox_dept.addItem("")
        self.comboBox_dept.addItem("")
        self.comboBox_dept.addItem("")
        self.comboBox_dept.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_dept)
        self.label_10 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_email = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_email.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_email.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_email)
        self.label_8 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_mobile = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_mobile.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_mobile.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_mobile.setObjectName("lineEdit_mobile")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit_mobile)
        self.label_7 = QtWidgets.QLabel(self.formFrame)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_11 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.radioButton_female = QtWidgets.QRadioButton(self.formFrame)
        self.radioButton_female.setObjectName("radioButton_female")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.radioButton_female)
        self.radioButton_male = QtWidgets.QRadioButton(self.formFrame)
        self.radioButton_male.setObjectName("radioButton_male")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.radioButton_male)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(200, 30, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.pushButton_create = QtWidgets.QPushButton(Form)
        self.pushButton_create.setGeometry(QtCore.QRect(50, 580, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_create.setFont(font)
        self.pushButton_create.setStyleSheet("background-color: rgb(248, 184, 120);")
        self.pushButton_create.setIcon(icon)
        self.pushButton_create.setIconSize(QtCore.QSize(50, 38))
        self.pushButton_create.setObjectName("pushButton_create")
        self.pushButton_clear = QtWidgets.QPushButton(Form)
        self.pushButton_clear.setGeometry(QtCore.QRect(320, 580, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setStyleSheet("background-color: rgb(77, 155, 232);")
        self.pushButton_clear.setObjectName("pushButton_clear")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Register!"))
        Form.setToolTip(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("Form", "Comp. Register Number"))
        self.label_4.setText(_translate("Form", "Name"))
        self.label_5.setText(_translate("Form", "Surname"))
        self.label_12.setText(_translate("Form", "Age"))
        self.label_2.setText(_translate("Form", "Username"))
        self.label_3.setText(_translate("Form", "Password"))
        self.label_6.setText(_translate("Form", "Department"))
        self.comboBox_dept.setItemText(0, _translate("Form", "Information Systems"))
        self.comboBox_dept.setItemText(1, _translate("Form", "Production"))
        self.comboBox_dept.setItemText(2, _translate("Form", "Human Resourse"))
        self.comboBox_dept.setItemText(3, _translate("Form", "Purchasing"))
        self.comboBox_dept.setItemText(4, _translate("Form", "Accounting"))
        self.comboBox_dept.setItemText(5, _translate("Form", "Marketing"))
        self.comboBox_dept.setItemText(6, _translate("Form", "R&D"))
        self.label_10.setText(_translate("Form", "e-Mail"))
        self.label_8.setText(_translate("Form", "Mobile Phone"))
        self.label_11.setText(_translate("Form", "Gender"))
        self.radioButton_female.setText(_translate("Form", "Female"))
        self.radioButton_male.setText(_translate("Form", "Male"))
        self.label_9.setText(_translate("Form", "Registration"))
        self.pushButton_create.setText(_translate("Form", "Register"))
        self.pushButton_clear.setText(_translate("Form", "Clear"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
