# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recordadd_wine.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_wine(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(452, 609)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/bars.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: rgb(201, 230, 255);")
        self.pushButton_add_wine = QtWidgets.QPushButton(Form)
        self.pushButton_add_wine.setGeometry(QtCore.QRect(60, 520, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_add_wine.setFont(font)
        self.pushButton_add_wine.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-radius: 10px")
        self.pushButton_add_wine.setObjectName("pushButton_add_wine")
        self.Label_Status = QtWidgets.QLabel(Form)
        self.Label_Status.setGeometry(QtCore.QRect(160, 370, 91, 20))
        self.Label_Status.setText("")
        self.Label_Status.setObjectName("Label_Status")
        self.pushButton_clear_wine = QtWidgets.QPushButton(Form)
        self.pushButton_clear_wine.setGeometry(QtCore.QRect(230, 520, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_clear_wine.setFont(font)
        self.pushButton_clear_wine.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"border-radius: 10px")
        self.pushButton_clear_wine.setObjectName("pushButton_clear_wine")
        self.formFrame = QtWidgets.QFrame(Form)
        self.formFrame.setGeometry(QtCore.QRect(80, 70, 291, 431))
        self.formFrame.setStyleSheet("")
        self.formFrame.setObjectName("formFrame")
        self.formLayout = QtWidgets.QFormLayout(self.formFrame)
        self.formLayout.setSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_fix = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_fix.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_fix.setObjectName("lineEdit_fix")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_fix)
        self.label_2 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_vol = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_vol.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_vol.setObjectName("lineEdit_vol")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_vol)
        self.label_3 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_cit = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_cit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_cit.setObjectName("lineEdit_cit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_cit)
        self.label_4 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_res = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_res.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_res.setObjectName("lineEdit_res")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_res)
        self.label_5 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_chl = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_chl.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_chl.setText("")
        self.lineEdit_chl.setObjectName("lineEdit_chl")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_chl)
        self.label_7 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_free = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_free.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_free.setText("")
        self.lineEdit_free.setObjectName("lineEdit_free")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_free)
        self.label_8 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_totalsul = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_totalsul.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_totalsul.setText("")
        self.lineEdit_totalsul.setObjectName("lineEdit_totalsul")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_totalsul)
        self.label_9 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_densi = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_densi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_densi.setText("")
        self.lineEdit_densi.setObjectName("lineEdit_densi")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_densi)
        self.label_10 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_ph = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_ph.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_ph.setText("")
        self.lineEdit_ph.setObjectName("lineEdit_ph")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit_ph)
        self.label_11 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lineEdit_sulp = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_sulp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_sulp.setText("")
        self.lineEdit_sulp.setObjectName("lineEdit_sulp")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lineEdit_sulp)
        self.label_22 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.lineEdit_alco = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_alco.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_alco.setText("")
        self.lineEdit_alco.setObjectName("lineEdit_alco")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.lineEdit_alco)
        self.label_23 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.lineEdit_qual = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_qual.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_qual.setText("")
        self.lineEdit_qual.setObjectName("lineEdit_qual")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.lineEdit_qual)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(100, 30, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Add New Wine Quality Record"))
        self.pushButton_add_wine.setText(_translate("Form", "ADD"))
        self.pushButton_clear_wine.setText(_translate("Form", "CLEAR"))
        self.label.setText(_translate("Form", "fixed acidity"))
        self.label_2.setText(_translate("Form", "volatile acidity"))
        self.label_3.setText(_translate("Form", "citric acid"))
        self.label_4.setText(_translate("Form", "residual sugar"))
        self.label_5.setText(_translate("Form", "chlorides"))
        self.label_7.setText(_translate("Form", "free sulfur dioxide"))
        self.label_8.setText(_translate("Form", "total sulfur dioxide"))
        self.label_9.setText(_translate("Form", "density"))
        self.label_10.setText(_translate("Form", "pH"))
        self.label_11.setText(_translate("Form", "sulphates"))
        self.label_22.setText(_translate("Form", "alcohol"))
        self.label_23.setText(_translate("Form", "quality"))
        self.label_6.setText(_translate("Form", "Add New Wine Quality Record"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
