# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recordadd_retail.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_retail(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(486, 518)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/bars.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: rgb(226, 255, 244);")
        self.pushButton_add = QtWidgets.QPushButton(Form)
        self.pushButton_add.setGeometry(QtCore.QRect(90, 450, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-radius: 10px")
        self.pushButton_add.setObjectName("pushButton_add")
        self.Label_Status = QtWidgets.QLabel(Form)
        self.Label_Status.setGeometry(QtCore.QRect(160, 370, 91, 20))
        self.Label_Status.setText("")
        self.Label_Status.setObjectName("Label_Status")
        self.pushButton_clear = QtWidgets.QPushButton(Form)
        self.pushButton_clear.setGeometry(QtCore.QRect(250, 450, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"border-radius: 10px")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.formFrame = QtWidgets.QFrame(Form)
        self.formFrame.setGeometry(QtCore.QRect(90, 80, 331, 361))
        self.formFrame.setStyleSheet("")
        self.formFrame.setObjectName("formFrame")
        self.formLayout = QtWidgets.QFormLayout(self.formFrame)
        self.formLayout.setSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_invoiceno = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_invoiceno.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_invoiceno.setObjectName("lineEdit_invoiceno")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_invoiceno)
        self.label_4 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_stockcode = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_stockcode.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_stockcode.setObjectName("lineEdit_stockcode")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_stockcode)
        self.label_5 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_stockdesc = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_stockdesc.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_stockdesc.setText("")
        self.lineEdit_stockdesc.setObjectName("lineEdit_stockdesc")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_stockdesc)
        self.label_8 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_quantity = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_quantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_quantity.setText("")
        self.lineEdit_quantity.setObjectName("lineEdit_quantity")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_quantity)
        self.label_7 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_invoicedate = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_invoicedate.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_invoicedate.setText("")
        self.lineEdit_invoicedate.setObjectName("lineEdit_invoicedate")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_invoicedate)
        self.label_9 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_unitprice = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_unitprice.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_unitprice.setObjectName("lineEdit_unitprice")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_unitprice)
        self.label_3 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_customerid = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_customerid.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_customerid.setObjectName("lineEdit_customerid")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_customerid)
        self.label = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox_country = QtWidgets.QComboBox(self.formFrame)
        self.comboBox_country.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_country.setObjectName("comboBox_country")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.comboBox_country)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(120, 20, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Add New Online Retail Record"))
        self.pushButton_add.setText(_translate("Form", "ADD"))
        self.pushButton_clear.setText(_translate("Form", "CLEAR"))
        self.label_2.setText(_translate("Form", "Invoice No"))
        self.label_4.setText(_translate("Form", "Stock Code"))
        self.label_5.setText(_translate("Form", "Stock Description"))
        self.label_8.setText(_translate("Form", "Quantity"))
        self.label_7.setText(_translate("Form", "Invoice Date"))
        self.label_9.setText(_translate("Form", "Unit Price"))
        self.label_3.setText(_translate("Form", "Customer ID"))
        self.label.setText(_translate("Form", "Country"))
        self.label_6.setText(_translate("Form", "Add New Online Retail Record"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
