# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recordadd_sales.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_sales(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(420, 498)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/bars.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: rgb(220, 213, 255);")
        self.pushButton_add_sales = QtWidgets.QPushButton(Form)
        self.pushButton_add_sales.setGeometry(QtCore.QRect(40, 420, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_add_sales.setFont(font)
        self.pushButton_add_sales.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-radius: 10px")
        self.pushButton_add_sales.setObjectName("pushButton_add_sales")
        self.pushButton_clear_sales = QtWidgets.QPushButton(Form)
        self.pushButton_clear_sales.setGeometry(QtCore.QRect(210, 420, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_clear_sales.setFont(font)
        self.pushButton_clear_sales.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"border-radius: 10px")
        self.pushButton_clear_sales.setObjectName("pushButton_clear_sales")
        self.formFrame = QtWidgets.QFrame(Form)
        self.formFrame.setGeometry(QtCore.QRect(60, 100, 321, 311))
        self.formFrame.setStyleSheet("")
        self.formFrame.setObjectName("formFrame")
        self.formLayout = QtWidgets.QFormLayout(self.formFrame)
        self.formLayout.setSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_store = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_store.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_store.setObjectName("lineEdit_store")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_store)
        self.label_2 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_product = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_product.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_product.setObjectName("lineEdit_product")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_product)
        self.label_3 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_date = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_date.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_date.setObjectName("lineEdit_date")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_date)
        self.label_4 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.radioButton_TRUE = QtWidgets.QRadioButton(self.formFrame)
        self.radioButton_TRUE.setObjectName("radioButton_TRUE")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.radioButton_TRUE)
        self.radioButton_FALSE = QtWidgets.QRadioButton(self.formFrame)
        self.radioButton_FALSE.setObjectName("radioButton_FALSE")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.radioButton_FALSE)
        self.label_5 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_baseprice = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_baseprice.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_baseprice.setText("")
        self.lineEdit_baseprice.setObjectName("lineEdit_baseprice")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_baseprice)
        self.label_8 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_7 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_weekly = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_weekly.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_weekly.setText("")
        self.lineEdit_weekly.setObjectName("lineEdit_weekly")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_weekly)
        self.lineEdit_price = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_price.setText("")
        self.lineEdit_price.setObjectName("lineEdit_price")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_price)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(120, 30, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Add New Sales Record"))
        self.pushButton_add_sales.setText(_translate("Form", "ADD"))
        self.pushButton_clear_sales.setText(_translate("Form", "CLEAR"))
        self.label.setText(_translate("Form", "STORE"))
        self.label_2.setText(_translate("Form", "PRODUCT"))
        self.label_3.setText(_translate("Form", "DATE (YEAR)"))
        self.label_4.setText(_translate("Form", "IS HOLİDAY"))
        self.radioButton_TRUE.setText(_translate("Form", "TRUE"))
        self.radioButton_FALSE.setText(_translate("Form", "FALSE"))
        self.label_5.setText(_translate("Form", "BASE PRICE"))
        self.label_8.setText(_translate("Form", "PRICE"))
        self.label_7.setText(_translate("Form", "WEEKLY UNIT SOLDS"))
        self.label_6.setText(_translate("Form", "Add New Sales Record"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
